services:
  db:
    image: postgres:16-alpine
    container_name: pg_semwork
    restart: unless-stopped
    environment:
      POSTGRES_DB: avito_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: djh1987
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [ backend ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: semwork_app
    depends_on:
      - db
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/avito_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: djh1987
    ports:
      - "8080:8080"
    networks: [ backend ]

volumes:
  pgdata:

networks:
  backend:
